### ISSUE TITLE
Error instance.destroy();

### ISSUE THREAD

**Issue by spruterkex** [bbc/peaks.js#284]
Hi! 

When trying do destroy the peaks instance. I get "TypeError: undefined is not an object (evaluating 'this._marks.length = 0')" as en error. Why is this happening? What is the correct way to release and destroy an instance?

I tried a workaround with 
instance.removeAllListeners();
instance.views.destroy();
instance.player.destroy();

This does not work. The player does not seem to be destroyed. I can still play the file at previous currentTime.

**Comment by chrisn** [comment]
I just fixed this error, in https://github.com/bbc/peaks.js/commit/c9264ca9eb8c8934c82a0240531dbefbeb344439.

**Comment by chrisn** [comment]
The `TypeError` is fixed in release 0.14.1. Please re-open if you still have problems after updating.

**Comment by spruterkex** [comment]
Hi! There still seems to be a problem since the player is still not destroyed. No TypeError but the player still plays.

**Comment by chrisn** [comment]
Destroying the Peaks instance simply detaches from the media element, so you'd have to stop the player yourself before destroying, if that's the behaviour you need.

**Comment by spruterkex** [comment]
Hi! Sorry, I wasn't clear. Peaks created the media element. If peaks detaches from the media element, shouldn't the player stop working? That is the behaviour I expected since I did not create the player myself, as peaks does this for me. (Thank you for all your help and replies!)

**Comment by chrisn** [comment]
Don't worry, I'm more than happy to fix this if there's a bug. We just need to figure out where it is! What problem is this causing for you in practice?

Peaks doesn't create media elements, it requires you to pass one in when calling `Peaks.init()`. `Peaks.init()` and `peaks.destroy()` aren't intended to change the state of the media element (e.g., to start or stop playback).

A Peaks instance is in something of an undefined state after calling `destroy()`. The main thing it does is remove event listeners from the media element, so that re-initialising Peaks in a single-page application works correctly. Or maybe you're suggesting that player methods should return errors or throw after `destroy()` has been called?

**Comment by spruterkex** [comment]
My mistake, I didn't mean that peaks creates the media element; peaks creates the player, not the media element itself. I pass the media element upon peaks.init(). My confusion concerning peaks.destroy() is that when I've called peaks.destroy() I can still play and stop my media element the same way as before peaks.destroy() was called, using instance.player.play() and instance.player.pause(). And if I call peaks.init() again, both the old media element and the new media element will play.

**Comment by chrisn** [comment]
OK, that's interesting. the player is only ever attached to a single media element, so I'm not sure how calling `instance.player.play()` would cause both elements to play. Do you have a code example you could share?

**Comment by spruterkex** [comment]
Even if I don't initiate peaks again, I can till call instance.player.play() and instance.player.pause(), with the result of the media element being played/paused, after i've called peaks.destroy().

**Comment by chrisn** [comment]
This is what I'd expect, and it's not clear it's a bug, as the instance is an undefined state. Your application should really discard the instance reference after calling `destroy()`:

```javascript
instance.destroy();
instance = null;
```
If it helps, we can add code to null the instance's media element reference, which will make further `play()` and `pause()` calls fail.
