### ISSUE TITLE
Doesn't run on windows

### ISSUE THREAD

**Issue by sonicviz** [bbc/peaks.js#328]
Thanks for the great library!
I've had some issues getting the demo running on windows, as noted below. 
After problem #3 the demo does actually work, though you need to serve it with a web server. 

Q: Is there any way of looping segments?

### Problem 1

npm start 
results in 

-loads of these errors
 84:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 11536 problems (11536 errors, 0 warnings)
  11536 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peaks.js@0.21.0 lint: `eslint src/*.js test/**/*.js test/*.js karma.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peaks.js@0.21.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paul\AppData\Roaming\npm-cache\_logs\2020-07-17T08_49_05_721Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peaks.js@0.21.0 prebuild: `npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peaks.js@0.21.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paul\AppData\Roaming\npm-cache\_logs\2020-07-17T08_49_05_737Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peaks.js@0.21.0 prestart: `npm run build && npm run copy-demo-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peaks.js@0.21.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paul\AppData\Roaming\npm-cache\_logs\2020-07-17T08_49_05_759Z-debug.log

Log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\paul\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.9.1-next.0
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle peaks.js@0.21.0~prestart: peaks.js@0.21.0
6 verbose lifecycle peaks.js@0.21.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle peaks.js@0.21.0~prestart: PATH: 
8 verbose lifecycle peaks.js@0.21.0~prestart: CWD: E:\Source Control\WebAudio\peaks.js
9 silly lifecycle peaks.js@0.21.0~prestart: Args: [ '/d /s /c', 'npm run build && npm run copy-demo-files' ]
10 silly lifecycle peaks.js@0.21.0~prestart: Returned: code: 1  signal: null
11 info lifecycle peaks.js@0.21.0~prestart: Failed to exec prestart script
12 verbose stack Error: peaks.js@0.21.0 prestart: `npm run build && npm run copy-demo-files`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Users\paul\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:315:20)
12 verbose stack     at ChildProcess.<anonymous> (C:\Users\paul\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid peaks.js@0.21.0
14 verbose cwd E:\Source Control\WebAudio\peaks.js
15 verbose Windows_NT 10.0.19041
16 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\paul\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
17 verbose node v12.18.2
18 verbose npm  v6.9.1-next.0
19 error code ELIFECYCLE
20 error errno 1
21 error peaks.js@0.21.0 prestart: `npm run build && npm run copy-demo-files`
21 error Exit status 1
22 error Failed at the peaks.js@0.21.0 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

### Solution
Change   to  'linebreak-style': ['error', 'windows'], in .eslintrc.js run eslint --fix
as per suggesiton in https://github.com/microsoft/vscode-eslint/issues/707#issuecomment-516989478

the run npm start again now gives the following error:
'cp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peaks.js@0.21.0 postbuild: `cp peaks.js demo && cp peaks.js.map demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peaks.js@0.21.0 postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paul\AppData\Roaming\npm-cache\_logs\2020-07-17T09_02_16_723Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peaks.js@0.21.0 prestart: `npm run build && npm run copy-demo-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peaks.js@0.21.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paul\AppData\Roaming\npm-cache\_logs\2020-07-17T09_02_16_745Z-debug.log

### Problem 2

Change cp to copy
Still gets an error on npm start

> copy test_data/sample.mp3 demo && copy test_data/07023003.mp3 demo && copy test_data/07023003-2channel.dat demo

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peaks.js@0.21.0 copy-demo-files: `copy test_data/sample.mp3 demo && copy test_data/07023003.mp3 demo && copy test_data/07023003-2channel.dat demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peaks.js@0.21.0 copy-demo-files script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paul\AppData\Roaming\npm-cache\_logs\2020-07-17T09_14_01_348Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peaks.js@0.21.0 prestart: `npm run build && npm run copy-demo-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peaks.js@0.21.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Problem 3

Modified the build script to remove the file copy (did manually) and then npm start fails on 

> peaks.js@0.21.0 postbuild E:\Source Control\WebAudio\peaks.js
> copy peaks.js demo && copy peaks.js.map demo

        1 file(s) copied.
        1 file(s) copied.

> peaks.js@0.21.0 start E:\Source Control\WebAudio\peaks.js
> serve --listen 8080 --no-clipboard demo

ERROR: Could not parse E:\Source Control\WebAudio\peaks.js\demo\package.json as JSON: Unexpected token / in JSON at position 1233
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peaks.js@0.21.0 start: `serve --listen 8080 --no-clipboard demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peaks.js@0.21.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paul\AppData\Roaming\npm-cache\_logs\2020-07-17T09_32_11_681Z-debug.log

Demo works at this point though. 

### Suggestion

Would be great if this was cross-platform as a clone repo, makes it much easier to work with them. 
See also: 
https://eslint.org/docs/2.0.0/rules/linebreak-style
https://ourcodeworld.com/articles/read/615/learn-how-to-solve-the-npm-error-cp-is-not-recognized-as-an-internal-or-external-command-operable-program-or-batch-file

**Comment by chrisn** [comment]
Thank you for reporting this.

I have just pushed [a change](https://github.com/bbc/peaks.js/commit/135665a1ac54e80a650fdcfa3acf64d1e5ffe41b) that forces Unix line endings, which should fix the eslint errors, and [another](https://github.com/bbc/peaks.js/commit/a33b7485fe156af1099ae54d23b912d16c228871) to replace use of the `cp` command.

**Comment by sonicviz** [comment]
Thanks for the quick response. 

I pulled the changes but still getting the eslint errors
 84:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

**Comment by chrisn** [comment]
Simply pulling the changes isn't enough, as this doesn't apply the settings in .gitattributes. There may be a git command to do that, I'm not sure, but the easiest way is to clone the repo again.

**Comment by sonicviz** [comment]
Aok. Re-cloned, rebuilt, retested....all good. Ty for the quick response!

Quick question: is it possible to loop segments?

**Comment by chrisn** [comment]
Not currently, we only have a method for playing a segment once - `instance.player.playSegment()` - feel free to raise a separate issue as a feature request.

**Comment by sonicviz** [comment]
aok, ty
